# Generated by Django 6.0.3 on 2026-04-06 04:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ名')),
                ('category_type', models.CharField(choices=[('income', '収益'), ('expense', '費用')], max_length=10, verbose_name='種別')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='日付')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='金額')),
                ('event_type', models.CharField(choices=[('general', '一般'), ('salary', '給料日'), ('payment', '支払い'), ('income', '収入')], default='general', max_length=10, verbose_name='種別')),
                ('is_processed', models.BooleanField(default=False, verbose_name='処理済み')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': 'カレンダーイベント',
                'verbose_name_plural': 'カレンダーイベント',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カード名')),
                ('payment_day', models.IntegerField(verbose_name='支払い日')),
                ('closing_day', models.IntegerField(verbose_name='締め日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'クレジットカード',
                'verbose_name_plural': 'クレジットカード',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='金額')),
                ('description', models.CharField(max_length=200, verbose_name='説明')),
                ('period', models.CharField(choices=[('current', '負債（今期）'), ('next', '予定負債（来期）')], default='current', max_length=10, verbose_name='期間')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '負債',
                'verbose_name_plural': '負債',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='記録日時')),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='取引日')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='金額')),
                ('transaction_type', models.CharField(choices=[('income', '収益'), ('expense', '費用'), ('credit', 'クレジット'), ('reset', '所持金再設定'), ('salary', '給料')], max_length=10, verbose_name='種別')),
                ('credit_settled', models.BooleanField(default=False, verbose_name='精算済み')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備考')),
                ('possession_after', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='取引後所持金')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app.category', verbose_name='カテゴリ')),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app.creditcard', verbose_name='クレジットカード')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '取引履歴',
                'verbose_name_plural': '取引履歴',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='所持金')),
                ('scheduled_income', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='予定所持金')),
                ('salary_type', models.CharField(choices=[('fixed', '固定'), ('variable', '変動')], default='fixed', max_length=10, verbose_name='給料日タイプ')),
                ('salary_day', models.IntegerField(blank=True, null=True, verbose_name='給料日（固定）')),
                ('next_salary_date', models.DateField(blank=True, null=True, verbose_name='次の給料日')),
                ('last_payday_processed', models.DateField(blank=True, null=True, verbose_name='最終給料日処理日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザープロフィール',
                'verbose_name_plural': 'ユーザープロフィール',
            },
        ),
    ]
